## ------------------------------------------------------------------------------
## hdfs-config-k8s:
## ------------------------------------------------------------------------------
hdfs-config-k8s:
  ## Custom hadoop config keys passed to the hdfs configmap as extra keys.
  customHadoopConfig:
     coreSite: {}
      ## Set config key and value pairs, e.g.
      # hadoop.http.authentication.type: kerberos

     hdfsSite: {}
      ## Set config key and value pairs, e.g.
      # dfs.datanode.use.datanode.hostname: "false"

## ------------------------------------------------------------------------------
## hdfs-namenode-k8s:
## ------------------------------------------------------------------------------
hdfs-namenode-k8s:
  ## Name of the namenode start script in the config map.
  namenodeStartScript: format-and-run.sh

  ## A namenode start script that can have user specified content.
  ## Can be used to conduct ad-hoc operation as specified by a user.
  ## To use this, also set the namenodeStartScript variable above
  ## to custom-run.sh.
  customRunScript: |
    #!/bin/bash -x
    echo Write your own script content!
    echo This message will disappear in 10 seconds.
    sleep 10

  persistence:
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"

    ## To choose a suitable persistent volume from available static volumes, selectors
    ## are used.
    # selector:
    #   matchLabels:
    #     volume-type: hdfs-ssd

    accessMode: ReadWriteOnce

    size: 100Gi

  ## Node labels and tolerations for pod assignment
  nodeSelector: {}
  tolerations: []
  affinity: {}

## ------------------------------------------------------------------------------
## hdfs-datanode-k8s:
## ------------------------------------------------------------------------------
hdfs-datanode-k8s:
  persistence:
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"

    ## To choose a suitable persistent volume from available static volumes, selectors
    ## are used.
    # selector:
    #   matchLabels:
    #     volume-type: hdfs-ssd

    accessMode: ReadWriteOnce

    size: 100Mi

  ## Node labels and tolerations for pod assignment
  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Number of datanodes to create
  size: 1

## ------------------------------------------------------------------------------
## hdfs-krb5-k8s:
## ------------------------------------------------------------------------------
hdfs-krb5-k8s:
  persistence:
    ## Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    # storageClass: "-"

    ## To choose a suitable persistent volume from available static volumes, selectors
    ## are used.
    # selector:
    #   matchLabels:
    #     volume-type: hdfs-ssd

    accessMode: ReadWriteOnce

    size: 20Gi

  ## We use a 3rd party image built from https://github.com/gcavalcante8808/docker-krb5-server.
  ## TODO: The pod currently prints out the admin account in plain text.
  ## Supply an admin account password using a k8s secret.
  ## TODO: The auto-generated passwords might be weak due to low entropy.
  ## Increase entropy by running rngd or haveged.
  ## TODO: Using latest tag is not desirable. The current image does not have specific tags.
  ## Find a way to fix it.
  image:
    repository: gcavalcante8808/krb5-server

    tag: latest

    pullPolicy: IfNotPresent

  service:
    type: ClusterIP

    port: 88
## ------------------------------------------------------------------------------
## Global values affecting all sub-charts:
## ------------------------------------------------------------------------------
global:
  ## Parameters for determining which Unix user and group IDs to use in pods.
  ## Persistent volume permission may need to match these.
  podSecurityContext:
    enabled: false
    runAsUser: 0
    fsGroup: 1000

  ## Whether or not to enable default affinity setting.
  defaultAffinityEnabled: true

  ## Whether or not Kerberos support is enabled.
  kerberosEnabled: false

  ## Effective only if Kerberos is enabled. Override th name of the k8s
  ## ConfigMap containing the kerberos config file.
  ##
  # kerberosConfigMapOverride: kerberos-config

  ## Effective only if Kerberos is enabled. Name of the kerberos config file inside
  ## the config map.
  kerberosConfigFileName: krb5.conf

  ## Effective only if Kerberos is enabled. Override the name of the k8s Secret
  ## containing the kerberos keytab files of per-host HDFS principals.
  ## The secret should have multiple data items. Each data item name
  ## should be formatted as:
  ##    `HOST-NAME.keytab`
  ## where HOST-NAME should match the cluster node
  ## host name that each per-host hdfs principal is associated with.
  ##
  # kerberosKeytabsSecretOverride: hdfs-kerberos-keytabs

  ## Required to be non-empty if Kerberos is enabled. Specify your Kerberos realm name.
  ## This should match the realm name in your Kerberos config file.
  kerberosRealm: MYCOMPANY.COM

  ## Effective only if Kerberos is enabled. Enable protection of datanodes using
  ## the jsvc utility. See the reference doc at
  ## https://hadoop.apache.org/docs/r2.7.2/hadoop-project-dist/hadoop-common/SecureMode.html#Secure_DataNode
  jsvcEnabled: true

## Tags and conditions for triggering a group of relevant subcharts.
tags:
  ## Trigger all subcharts required for using Kerberos. Disabled by default.
  kerberos: false
